### ISSUE TITLE
sorted_list matcher

### ISSUE THREAD

**Issue by axelson** [mtrudel/machete#15]
Hi Mat!

Would you be interested in a `sorted_list` matcher?

I added one in https://github.com/ScenicFramework/scenic/pull/335 for Scenic, but it would be nice to upstream it.

I think it would complement the existing [InAnyOrderMatcher](https://hexdocs.pm/machete/0.2.8/Machete.InAnyOrderMatcher.html) because the InAnyOrderMatcher has an exponential cost and the sorted_list matcher would not. In many cases it won't make a big difference, but I generally try to avoid exponential costs when they can be avoided and in this case I think it can.

**Comment by mtrudel** [comment]
You and I had looked at this a while back I think, and the issue is that 'sorting' is only a thing that makes sense for literal values (this is why `InAnyOrderMatcher` is exponential, since something like `string()` could match any value and there aren't any super sensible ways to help that along with sorting). 

That being said, your use case makes perfect sense; I just wonder about a way to present this to users in a non-confusing way. I wonder; what if we had a `sortable: true` option to `InAnyOrderMatcher` that used your logic? That would result in one matcher for 'any order' matching, and would make it a mode vs a wholly separate matcher. I *think* that would be clearer? 

WDYT?

**Comment by mtrudel** [comment]
Most of this got solved with the recent changes in 0.3.4. Beyond that, I can't think of much of a way to expose this in a way that isn't super confusing to newcomers.

Gonna close for now in the name of hygiene. If you can think of something that works well here, feel free to open a new ticket! Thanks again!
